
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis Santillanes
 */
public class Principal extends javax.swing.JFrame {
    Graphics gpsMiDibu;
    int x,y, cont=-1;
    int xIni, yIni;
    Point coord = null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        gpsMiDibu = canDibu.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canDibu = new java.awt.Canvas();
        btnCerrarFig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canDibu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canDibuMouseClicked(evt);
            }
        });

        btnCerrarFig.setText("Cerrar figura");
        btnCerrarFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canDibu, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarFig)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canDibu, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarFig)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void canDibuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canDibuMouseClicked
        //* =========== MI CODIGO ================
        contador();
        if(cont == 0){
            gpsMiDibu.drawOval(evt.getX()-2, evt.getY()-2, 4, 4);
            setX(evt.getX());
            setY(evt.getY());
            setxIni(evt.getX());
            setyIni(evt.getY());
        }else{
            gpsMiDibu.drawOval(evt.getX()-2, evt.getY()-2, 4, 4);
            gpsMiDibu.drawLine(getX(), getY(), evt.getX(), evt.getY());
            setX(evt.getX());
            setY(evt.getY());
        }// =========== MI CODIGO ================ 
        /*gpsMiDibu.setColor(Color.blue);
        gpsMiDibu.drawOval(evt.getX()-2, evt.getY()-2, 4, 4);
        if(coord != null){
            gpsMiDibu.drawLine(coord.x, coord.y, evt.getX(), evt.getY());
            coord.x = evt.getX();
            coord.y = evt.getY();
        }else{
            coord = new Point(evt.getX(), evt.getY());
        }*/
    }//GEN-LAST:event_canDibuMouseClicked

    private void btnCerrarFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFigActionPerformed
        //      ====== FUNCIONA CON MI CODIGO, NO CON EL DEL PROFE =============
        gpsMiDibu.drawLine(getxIni(), getyIni(), getX(), getY());
    }//GEN-LAST:event_btnCerrarFigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarFig;
    private java.awt.Canvas canDibu;
    // End of variables declaration//GEN-END:variables

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }

    public int contador(){
        return cont++;
    }

    public int getxIni() {
        return xIni;
    }

    public void setxIni(int xIni) {
        this.xIni = xIni;
    }

    public int getyIni() {
        return yIni;
    }

    public void setyIni(int yIni) {
        this.yIni = yIni;
    }

}


